### ISSUE TITLE
Trying to talk to CloudSQL Proxy binary (IAM User auth), with Golang code

### ISSUE THREAD

**Issue by esn89** [GoogleCloudPlatform/cloud-sql-proxy#2285]
### Bug Description

I have successfully started up CloudSQL binary on my VM:

```bash
./cloud-sql-proxy --auto-iam-authn --impersonate-service-account=demo-sa@mycompany.gserviceaccount.com --private-ip mycompany:us-central1:demodb --debug --debug-logs
```

I am able to login via `mysql` cli without any problems and it listens on localhost on 2206

Next, I would like to create a Golang application to do so by following this guide:
https://cloud.google.com/sql/docs/postgres/iam-logins#log-in-with-automatic 

But once I deploy my application and it serves and listen, it has issues when I submit a query:

```
INSERT INTO people VALUES(doodoodoo, 123)
[mysql] 2024/08/06 18:16:03 connector.go:146: could not use requested auth plugin 'mysql_native_password': this user requires mysql native password authentication
this user requires mysql native password authentication
2024/08/06 18:16:03 http: panic serving 127.0.0.1:48636: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1()
	/opt/local/lib/go/src/net/http/server.go:1903 +0xbe
panic({0xaff6c0?, 0x11a13e0?})
	/opt/local/lib/go/src/runtime/panic.go:770 +0x132
database/sql.(*Rows).closemuRUnlockIfHeldByScan(0x38?)
	/opt/local/lib/go/src/database/sql/sql.go:3366 +0xe
database/sql.(*Rows).Close(0x0)
	/opt/local/lib/go/src/database/sql/sql.go:3393 +0x18
api-cloudsql/pkg/controllers.CreatePerson({0xd00410, 0xc0000f0a80}, 0xc00034cea0)
	/Users/evng/Documents/Projects/api-cloudsql/pkg/controllers/controllers.go:34 +0x2ed
net/http.HandlerFunc.ServeHTTP(0xc00034cd80?, {0xd00410?, 0xc0000f0a80?}, 0x1?)
	/opt/local/lib/go/src/net/http/server.go:2171 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000001b00, {0xd00410, 0xc0000f0a80}, 0xc00034c900)
	/Users/evng/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
net/http.serverHandler.ServeHTTP({0xcfe198?}, {0xd00410?, 0xc0000f0a80?}, 0x6?)
	/opt/local/lib/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc0000e1c20, {0xd01390, 0xc000354ab0})
	/opt/local/lib/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
	/opt/local/lib/go/src/net/http/server.go:3290 +0x4b4
Shared connection to compute.925502400976046099 closed.
```

I have used `demo-sa@mycompany.gserviceaccount.com` as the dbUser

### Example code (or command)

```golang
import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"net"
	"os"

	"cloud.google.com/go/cloudsqlconn"

	"github.com/go-sql-driver/mysql"
	_ "github.com/go-sql-driver/mysql"
)

func ConnectWithConnectorIAMAuthN() (*sql.DB, error) {
	mustGetenv := func(k string) string {
		v := os.Getenv(k)
		if v == "" {
			log.Fatalf("Warning: %s environment variable not set.", k)
		}
		return v
	}
	// Note: Saving credentials in environment variables is convenient, but not
	// secure - consider a more secure solution such as
	// Cloud Secret Manager (https://cloud.google.com/secret-manager) to help
	// keep secrets safe.
	var (
		dbUser                 = mustGetenv("DB_IAM_USER")              // e.g. 'service-account-name@project-id.iam'
		dbName                 = mustGetenv("DB_NAME")                  // e.g. 'my-database'
		instanceConnectionName = mustGetenv("INSTANCE_CONNECTION_NAME") // e.g. 'project:region:instance'
		usePrivate             = os.Getenv("PRIVATE_IP")
	)

	d, err := cloudsqlconn.NewDialer(context.Background(), cloudsqlconn.WithIAMAuthN())
	if err != nil {
		return nil, fmt.Errorf("cloudsqlconn.NewDialer: %w", err)
	}
	var opts []cloudsqlconn.DialOption
	if usePrivate != "" {
		opts = append(opts, cloudsqlconn.WithPrivateIP())
	}

	// creates a new config
	cfg := mysql.Config{
		User:   dbUser,
		Addr:   "127.0.0.1:3306",
		DBName: dbName,
	}
	dsn := cfg.FormatDSN()

	mysql.RegisterDialContext("cloudsqlconn",
		func(ctx context.Context, instance string) (net.Conn, error) {
			return d.Dial(ctx, instanceConnectionName, opts...)
		})

	dbPool, err := sql.Open("mysql", dsn)
	if err != nil {
		return nil, fmt.Errorf("sql.Open: %w", err)
	}
	return dbPool, nil
}
```

### Stacktrace

```bash
DB_IAM_USER=demo-sa@mycompany.iam.gserviceaccount.com DB_NAME=trial INSTANCE_CONNECTION_NAME=mycompany:us-central1:demodb PRIVATE_IP=yes ./api-cloudsql
INSERT INTO people VALUES(doodoodoo, 123)
[mysql] 2024/08/06 18:16:03 connector.go:146: could not use requested auth plugin 'mysql_native_password': this user requires mysql native password authentication
this user requires mysql native password authentication
2024/08/06 18:16:03 http: panic serving 127.0.0.1:48636: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1()
	/opt/local/lib/go/src/net/http/server.go:1903 +0xbe
panic({0xaff6c0?, 0x11a13e0?})
	/opt/local/lib/go/src/runtime/panic.go:770 +0x132
database/sql.(*Rows).closemuRUnlockIfHeldByScan(0x38?)
	/opt/local/lib/go/src/database/sql/sql.go:3366 +0xe
database/sql.(*Rows).Close(0x0)
	/opt/local/lib/go/src/database/sql/sql.go:3393 +0x18
api-cloudsql/pkg/controllers.CreatePerson({0xd00410, 0xc0000f0a80}, 0xc00034cea0)
	/Users/evng/Documents/Projects/api-cloudsql/pkg/controllers/controllers.go:34 +0x2ed
net/http.HandlerFunc.ServeHTTP(0xc00034cd80?, {0xd00410?, 0xc0000f0a80?}, 0x1?)
	/opt/local/lib/go/src/net/http/server.go:2171 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000001b00, {0xd00410, 0xc0000f0a80}, 0xc00034c900)
	/Users/evng/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
net/http.serverHandler.ServeHTTP({0xcfe198?}, {0xd00410?, 0xc0000f0a80?}, 0x6?)
	/opt/local/lib/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc0000e1c20, {0xd01390, 0xc000354ab0})
	/opt/local/lib/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
	/opt/local/lib/go/src/net/http/server.go:3290 +0x4b4
Shared connection to compute.925502400976046099 closed.
```
```


### Steps to reproduce?

1. Create the CloudSQL with automatic auth, impersonate the service account and with private IP
2. Create a DB listener in GoLang using my code
3. Try to write a query



### Environment

1. OS type and version: Linux 
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`):
3. ./cloud-sql-proxy --auto-iam-authn --impersonate-service-account=mycompany@panw-sls-dev.iam.gserviceaccount.com --private-ip panw-sls-dev:us-central1:demodb --debug --debug-logs

### Additional Details

I have already granted CloudSQL Instance User and client.

On the `mysql` command line there are no issues.

I even granted the demo-sa user `cloudsqlsuperuser` role via `GRANTS`

**Comment by jackwotherspoon** [comment]
Hi @esn89, thanks for raising an issue on the Cloud SQL Proxy! 😄 

Let me try and help you out.

The [Cloud SQL Proxy](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/) (this repo) is a language agnostic binary that can be run alongside an application to give it access to secure connections to Cloud SQL. Our team also ships native packages in Go, Java, Node, and Python that achieve the same benefits and features of the Proxy. 

From this repo's [README](https://github.com/GoogleCloudPlatform/cloud-sql-proxy):
> If you're using Go, Java, Python, or Node.js, consider using the corresponding Cloud SQL Connector language 
> library which does everything the Proxy does, but as in process native packages:
>
> [Cloud SQL Go connector](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector)
> [Cloud SQL Java connector](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory)
> [Cloud SQL Python connector](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector)
> [Cloud SQL Node.js connector](https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector)

From the description of your issue it seems you are attempting to use the Cloud SQL Proxy and the Cloud SQL Go Connector package ([cloud.google.com/go/cloudsqlconn](https://pkg.go.dev/cloud.google.com/go/cloudsqlconn)) in combination. This not recommended since both achieve the same functionality. 

You should use one or the other:

### Cloud SQL Proxy

To use just the Proxy remove all the Go Connector code and connect purely with [database/sql](https://github.com/go-sql-driver/mysql) driver like this:

```go
cfg := mysql.Config{
    User:   dbUser,
    Addr:   "127.0.0.1:3306",
    DBName: dbName,
}
dsn := cfg.FormatDSN()

dbPool, err := sql.Open("mysql", dsn)
```

I'll look for the service account impersonation usage for the Cloud SQL Go Connector and add it here as a second option when I do.

**Comment by esn89** [comment]
oh my god.  

Thank you, I have been overcomplicating things SO much.

So I now understand this better:

Either I use a CloudSQL Sidecar/Binary, and talk to it via MySQL GoLang Library over simple 127.0.0.1 and nothing else.  Just simple connector/dialer.

Or I do NOT use the CloudSQL Sidecar/Binary and I will need all of this CURRENT connector code.

**Comment by jackwotherspoon** [comment]
> So I now understand this better:
> 
> Either I use a CloudSQL Sidecar/Binary, and talk to it via MySQL GoLang Library over simple 127.0.0.1 and nothing else. Just simple connector/dialer.
> 
> Or I do NOT use the CloudSQL Sidecar/Binary and I will need all of this CURRENT connector code.

@esn89 That is correct! You've got the gist of it 😄 

I have added the Go Connector sample for service account impersonation to my above comment to see the two different implementations side by side (Proxy vs Go Connector).

**Comment by esn89** [comment]
Thanks @jackwotherspoon .

I have shrunk my code and made is significantly less complex:

``golang
func ConnectToCloudSQL() (*sql.DB, error) {
	mustGetenv := func(k string) string {
		v := os.Getenv(k)
		if v == "" {
			log.Fatalf("Warning: %s environment variable not set.", k)
		}
		return v
	}
	// Note: Saving credentials in environment variables is convenient, but not
	// secure - consider a more secure solution such as
	// Cloud Secret Manager (https://cloud.google.com/secret-manager) to help
	// keep secrets safe.
	var (
		dbUser = mustGetenv("DB_IAM_USER") // e.g. 'service-account-name@project-id.iam'
		dbName = mustGetenv("DB_NAME")     // e.g. 'my-database'
	)

	// creates a new config
	cfg := mysql.Config{
		User:   dbUser,
		Addr:   "127.0.0.1:3306",
		DBName: dbName,
	}
	dsn := cfg.FormatDSN()

	dbPool, err := sql.Open("mysql", dsn)
	if err != nil {
		return nil, fmt.Errorf("sql.Open: %w", err)
	}
	return dbPool, nil
}
```

However, I am still having issues:

CloudSQL Proxy running in the background like so:
`./cloud-sql-proxy --auto-iam-authn --impersonate-service-account=demo-sa@mycompany.iam.gserviceaccount.com --private-ip mycompany:us-central1:demodb --debug --debug-logs`

I started my code like so:
`DB_IAM_USER=demo-sa@mycompany.iam.gserviceaccount.com DB_NAME=trial  ./api-cloudsql`

I then tested it on the VM using simple `mysql`, and that seems to work:

```
mysql -h 127.0.0.1 --user=demo-sa
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 40708
Server version: 8.0.31-google (Google)

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

**Comment by jackwotherspoon** [comment]
> I started my code like so:
DB_IAM_USER=demo-sa@mycompany.iam.gserviceaccount.com DB_NAME=trial  ./api-cloudsql

For MySQL IAM DB user are truncated to everything before the `@` so I think changing `DB_IAM_USER` will fix your issue:

```
DB_IAM_USER=demo-sa DB_NAME=trial  ./api-cloudsql
```

Try that and see if it works now 🤞

**Comment by esn89** [comment]
Still no luck:

```
umpbox:~$ DB_IAM_USER=demo-sa DB_NAME=trial  ./api-cloudsql
^[[CINSERT INTO people VALUES(evan, 123)
[mysql] 2024/08/07 16:06:33 connector.go:146: could not use requested auth plugin 'mysql_native_password': this user requires mysql native password authentication
this user requires mysql native password authentication
2024/08/07 16:06:33 http: panic serving 127.0.0.1:59740: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1()
	/opt/local/lib/go/src/net/http/server.go:1903 +0xbe
panic({0x6b6540?, 0x942480?})
	/opt/local/lib/go/src/runtime/panic.go:770 +0x132
database/sql.(*Rows).closemuRUnlockIfHeldByScan(0x38?)
	/opt/local/lib/go/src/database/sql/sql.go:3366 +0xe
database/sql.(*Rows).Close(0x0)
	/opt/local/lib/go/src/database/sql/sql.go:3393 +0x18
api-cloudsql/pkg/controllers.CreatePerson({0x784b30, 0xc0000fe0e0}, 0xc0000ceb40)
	/Users/evng/Documents/Projects/api-cloudsql/pkg/controllers/controllers.go:34 +0x2ed
net/http.HandlerFunc.ServeHTTP(0xc0000cea20?, {0x784b30?, 0xc0000fe0e0?}, 0x1?)
	/opt/local/lib/go/src/net/http/server.go:2171 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f4000, {0x784b30, 0xc0000fe0e0}, 0xc0000ce5a0)
	/Users/evng/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
net/http.serverHandler.ServeHTTP({0x783dd0?}, {0x784b30?, 0xc0000fe0e0?}, 0x6?)
	/opt/local/lib/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc000156000, {0x7851c0, 0xc00009b320})
	/opt/local/lib/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
	/opt/local/lib/go/src/net/http/server.go:3290 +0x4b4
```

**Comment by enocom** [comment]
I believe this is a quirk of MySQL.

Try adding `AllowNativePasswords: true` to your MySQL configuration.

**Comment by esn89** [comment]
@enocom the error went away.  Thank you.

**Comment by esn89** [comment]
I managed to get this to work with:

```golang
func ConnectToCloudSQL() (*sql.DB, error) {
	mustGetenv := func(k string) string {
		v := os.Getenv(k)
		if v == "" {
			log.Fatalf("Warning: %s environment variable not set.", k)
		}
		return v
	}
	// Note: Saving credentials in environment variables is convenient, but not
	// secure - consider a more secure solution such as
	// Cloud Secret Manager (https://cloud.google.com/secret-manager) to help
	// keep secrets safe.
	var (
		dbUser = mustGetenv("DB_IAM_USER") // e.g. 'service-account-name@project-id.iam'
		dbName = mustGetenv("DB_NAME")     // e.g. 'my-database'
	)
	fmt.Printf("My dbUser is %s and my dbName is %s", dbUser, dbName)
	// creates a new config
	cfg := mysql.Config{
		User:                 dbUser,
		Addr:                 "127.0.0.1:3306",
		DBName:               dbName,
		AllowNativePasswords: true,
	}
	dsn := cfg.FormatDSN()

	dbPool, err := sql.Open("mysql", dsn)
	if err != nil {
		return nil, fmt.Errorf("sql.Open: %w", err)
	}
	return dbPool, nil
}
```

Thank you to @enocom  and @jackwotherspoon

**Comment by enocom** [comment]
Glad to hear it. Thanks for sharing the final details -- that will help other folks who hit this.
